backend:
  name: git-gateway
  repo: the-stack/jobs4students-22-fe-nuxt
  branch: master # Branch to update (optional; defaults to master)
  locale: 'en'

local_backend: true
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

site_url: https://chic-florentine-ad2e6e.netlify.app/
display_url: https://chic-florentine-ad2e6e.netlify.app/

collections:
  - name: "intro" # Used in routes, e.g., /admin/collections/blog
    label: "Einleitung" # Used in the UI
    folder: "content/_index" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "intro" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
